### ISSUE TITLE
Missing Monaco lib and grafana is strongly outdated

### ISSUE THREAD

**Issue by kojuki** [openshift/grafana#86]
**What happened**: all Grafana images in registry.redhat.io, what contains Grafana older than 7.5.5 missing Monaco library (it was removed by one of commits). As a result in creating/editing dashboards it’s not possible to see query. Metric browser works fine, but query field does not loading (shows “loading…”).

**What you expected to happen**:monaco library present as in original Grafana package. Query field loaded successfully.

**How to reproduce it (as minimally and precisely as possible)**: run redhat registry grafana image (latest, for example) in ose4. (Probably pod should be also isolated from internet)

**Anything else we need to know?**: lib presents in images with grafana up to 7.5.5 and absent in images with grafana newer than 7.5.5. Was deleted by one of commit. Also grafana version is strongly outdated.

**Environment**:
- Grafana version:8.3.4
- Data source type & version:any
- OS Grafana is installed on:ose4
- User OS & Browser:any
- Grafana plugins:any
- Others:

**Comment by wtfc63** [comment]
The Monaco library is still missing in the `latest` and `release` versions (or `4.11.0` at the moment) and therefore, the query editor is currently still unusable!

Grafana will try to load the editor from `/public/lib/monaco/min/vs/loader.js`, but get an HTTP 404 since it is not present in `/usr/share/grafana/public/lib`.

/reopen
